### ISSUE TITLE
Set package description

### ISSUE THREAD

**Issue by simondel** [nicojs/typed-html#3]
No description has been set in the package.json so Visual Studio code will just try to load the readme:
![image](https://user-images.githubusercontent.com/4221997/33553572-9a870388-d8f9-11e7-8a14-51445aaad8ba.png)

This is what it looks like with a description:
![image](https://user-images.githubusercontent.com/4221997/33553589-af8a34d0-d8f9-11e7-9d9d-9b29ec034400.png)

**Comment by nicojs** [comment]
What's wrong with that?  :smirk:

thanks
